services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: stage
      POSTGRES_PASSWORD: stage123
      POSTGRES_DB: stage_processos
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
volumes:
  dbdata:
